### ISSUE TITLE
COURSE3 - Create a Course Data Model

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/educationPortal#5]
Create a schema and data model to represent courses. Attributes should be:

title: String
createdDate: Date
author: ref: UserModel
description: String

API:

createCourse(course);
deleteCourse(courseId);
updateCourse(courseId, course);
findCourseById(courseId);
findCourseByTitle(title);

**Comment by Swayambita-Das** [comment]
Issue resolved. All required schema, model and API present.
