### ISSUE TITLE
COURSE4 - Course REST API

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/educationPortal#6]
Create a REST api to expose Course data model

POST /api/course, {course} createCourse
PUT /api/course/:courseId, {course} updateCourse
DELETE /api/course/:courseId, deleteCourse
GET /api/course, findAllCourses()
GET /api/course/:courseId, findCourseById()

later:
GET /api/user/:userId/course, findCourseByAuthor(userId)...later

**Comment by Swayambita-Das** [comment]
@priyankadshenoy This is part of the course module am doing, I have already finish few of these.
