### ISSUE TITLE
SECTION1 - Create Section Data Model

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/educationPortal#7]
Each Course instance will have many sections. Create a data model for section

{
title: String,
_course: ObjectId, ref: CourseModel
startDate: Date,
endDate: Date,
code: String
}

createSection(section)
deleteSection(sectionId)
updateSection(sectionId, section)
findSectionById(sectionId)
findSectionByCourse(courseId) - return all sections for a course

**Comment by Swayambita-Das** [comment]
Issue can be closed. All requirements satisfied.
