### ISSUE TITLE
SECTION2 - Create REST API for Section

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/educationPortal#8]
POST /api/course/:courseId/section, section, createSection(section)
GET /api/course/:courseId/section, findAllSectionForCourse(courseId)
GET /api/section/:sectionId, findSectionById(sectionId)
PUT /api/section/:sectionId, section, updateSection(sectionId, section)
DELETE /api/section/:sectionId, deleteSection(sectionId)

**Comment by Swayambita-Das** [comment]
Issue can be closed.
